-- Character
NDefines.NCharacter.MAX_WARDS_PER_GUARDIAN = 4
NDefines.NCharacter.CHANGE_FOCUS_YEARS = 1
NDefines.NCharacter.MAX_GENERATED_TRAITS_FOR_HISTORICAL = 10
NDefines.NCharacter.BASE_NR_OF_CHILDREN_PER_COUPLE = 5
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_0 = 25
NDefines.NCharacter.AGE_ADOLESCENT = 10